# Generated by Django 4.1.1 on 2023-07-19 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('reference', models.CharField(error_messages={'unique': 'Ya existe un proyecto con esa referencia'}, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('year', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(2023), django.core.validators.MinValueValidator(2000)])),
                ('convocatory', models.CharField(max_length=400)),
                ('area', models.CharField(max_length=100)),
                ('subarea', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=400)),
                ('cif', models.CharField(max_length=100)),
                ('ccaa', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('money', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('idScopus', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=400)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2000), django.core.validators.MinValueValidator(2023)])),
                ('source', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=100, null=True)),
                ('issue', models.PositiveIntegerField(null=True)),
                ('start', models.PositiveIntegerField(blank=True, null=True)),
                ('end', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(max_length=100, null=True)),
                ('cited', models.PositiveIntegerField(default=0)),
                ('RAW', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
